cask "static-font-cormorant" do
  # Placeholder zero, followed by svn revision
  version "0,321"
  sha256 :no_check

  url "https://github.com/CatharsisFonts/Cormorant/tree/master/2. OpenType Files",
      using:    :svn,
      revision: version.after_comma.to_s
  name "Cormorant Garamond"
  desc "Static OTF fonts from the Cormorant family"
  homepage "https://github.com/CatharsisFonts/Cormorant"

  font "Cormorant-Bold.otf"
  font "Cormorant-BoldItalic.otf"
  font "Cormorant-Italic.otf"
  font "Cormorant-Light.otf"
  font "Cormorant-LightItalic.otf"
  font "Cormorant-Medium.otf"
  font "Cormorant-MediumItalic.otf"
  font "Cormorant-Regular.otf"
  font "Cormorant-SemiBold.otf"
  font "Cormorant-SemiBoldItalic.otf"
  font "CormorantGaramond-Bold.otf"
  font "CormorantGaramond-BoldItalic.otf"
  font "CormorantGaramond-Italic.otf"
  font "CormorantGaramond-Light.otf"
  font "CormorantGaramond-LightItalic.otf"
  font "CormorantGaramond-Medium.otf"
  font "CormorantGaramond-MediumItalic.otf"
  font "CormorantGaramond-Regular.otf"
  font "CormorantGaramond-SemiBold.otf"
  font "CormorantGaramond-SemiBoldItalic.otf"
  font "CormorantInfant-Bold.otf"
  font "CormorantInfant-BoldItalic.otf"
  font "CormorantInfant-Italic.otf"
  font "CormorantInfant-Light.otf"
  font "CormorantInfant-LightItalic.otf"
  font "CormorantInfant-Medium.otf"
  font "CormorantInfant-MediumItalic.otf"
  font "CormorantInfant-Regular.otf"
  font "CormorantInfant-SemiBold.otf"
  font "CormorantInfant-SemiBoldItalic.otf"
  font "CormorantSC-Bold.otf"
  font "CormorantSC-Light.otf"
  font "CormorantSC-Medium.otf"
  font "CormorantSC-Regular.otf"
  font "CormorantSC-SemiBold.otf"
  font "CormorantUnicase-Bold.otf"
  font "CormorantUnicase-Light.otf"
  font "CormorantUnicase-Medium.otf"
  font "CormorantUnicase-Regular.otf"
  font "CormorantUnicase-SemiBold.otf"
  font "CormorantUpright-Bold.otf"
  font "CormorantUpright-Light.otf"
  font "CormorantUpright-Medium.otf"
  font "CormorantUpright-Regular.otf"
  font "CormorantUpright-SemiBold.otf"
end
